services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5065:5065"
    restart: always
    volumes:
      - registry_data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5065
      REGISTRY_HTTP_SECRET: your-local-registry-secret-key

volumes:
  registry_data: