"""§12.1 ABJ-trace anomalies as provable impossibility proofs.

Physics origin (Adler-Bell-Jackiw 1969; 't Hooft 1980): a classical
symmetry generated by ``T^a`` survives quantization iff the anomaly
polynomial

    A^{abc} = Tr( T^a {T^b, T^c} )

vanishes for every triple ``(a, b, c)``. A nonzero anomaly is a *positive
obstruction*: no consistent quantum theory carries that symmetry. This is
how physicists prove certain theories are impossible — by detecting an
obstruction in the operator algebra, not by exhaustive search.

QPCN realization (spec §12.1): the typing Hamiltonian's per-rule factored
projectors are **leaf-local generators** that classically commute with the
ground-state manifold (well-typed programs). An ill-typed program breaks
the symmetry not by vacuum choice (Goldstone, §12.6) and not by branch
multiplicity (topological degeneracy, §12.3) but by an algebraic
obstruction in the projector triple ``Tr( P_kind { P_type, P_value } )``
evaluated on the leaf marginal. When the typing rule's kind/type/value
expectations cannot simultaneously align with their well-typed values,
the ABJ trace fires and the theorem is provably unprovable.

This module is operator-algebraic (§1.1 anti-shortcut): symmetry
generators are read off the typing Hamiltonian's factored projector
operators, NOT from the AST. The anomaly trace is evaluated on the real
MERA leaf marginals through ``state.leaf_marginal`` and
``mera_window_expectation_factored`` — never via dense ``16**k`` operator
construction (§1.3), never via AST symbol parsing.

Cost: per generator, a constant number of factored window expectations
on the state, polynomial in ``meta.n_nodes`` and the number of rules. The
trace itself reduces to products of single-leaf expectations on a
product MERA via the §1.2 factorization, so the whole computation is
``O(N_rules · N_nodes)`` window evaluations — cheap relative to the
proof search.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from src.qft_pcn.logic._mera_typing_rules import (
    leaf_proj, leaf_proj_one_minus, leaf_proj_set, leaf_identity,
)
from src.qft_pcn.logic._mera_window import mera_window_expectation_factored
from src.qft_pcn.logic.mera_encoding import (
    KIND_PAD, KIND_VAR, KIND_LAM, KIND_APP, KIND_INT, KIND_BOOL,
    KIND_IF, KIND_BIN, KIND_ZERO, KIND_SUCC, KIND_NATLIT,
    KIND_NIL, KIND_CONS, KIND_EQ, KIND_FORALL, KIND_FIX,
    TYPE_NAT, TYPE_LIST, TYPE_PROP,
)
from src.qft_pcn.logic.encoding import (
    TYPE_INT, TYPE_BOOL,
    TYPE_ARR_II, TYPE_ARR_IB, TYPE_ARR_BI, TYPE_ARR_BB,
    VALUE_PLUS, VALUE_MINUS, VALUE_TIMES, VALUE_LT, VALUE_EQ,
)
from src.qft_pcn.logic.mera_typing_hamiltonian import (
    MeraTypingHamiltonian,
    RULE_T_LIT_INT, RULE_T_LIT_BOOL, RULE_T_BIN_ARITH, RULE_T_BIN_CMP,
    RULE_T_ZERO, RULE_T_NATLIT, RULE_T_NIL,
)
from src.qft_pcn.qft.mera import MERA


# ---------------------------------------------------------------------------
# Default thresholds
# ---------------------------------------------------------------------------

# An ABJ trace below this is considered "anomaly-free" (the theorem may
# or may not be provable; the anomaly check is silent). The constant is
# the same residual floor used by the Goldstone diagnostic (§12.6) so
# the two impossibility/missing-lemma codes share a single
# zero-energy convention.
DEFAULT_ANOMALY_FLOOR = 1e-6


# ---------------------------------------------------------------------------
# Symmetry generators
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SymmetryGenerator:
    """A leaf-local generator of a candidate typing symmetry.

    A typing rule (e.g. ``T-Lit-Int``) constrains an AST node's *type*
    leaf to be consistent with its *kind* leaf. The classical symmetry
    is: "permute the kind/type pair on the node's window in the way that
    leaves the rule satisfied." Its generator is a triple of leaf-local
    projectors

        ``T^a = (P_kind, P_type, P_value)``

    each living on a different leaf of the node's window. Identity on
    unlisted species. ``rule_id`` and ``node`` address the generator
    against the originating Hamiltonian term so anomaly results can be
    surfaced back to the source location (spec §12.1: "return certificate
    with the obstruction's algebraic signature").

    The projectors are stored as a dict ``{leaf_index: (16, 16) matrix}``,
    matching the factored-operator window contract of
    :func:`mera_window_expectation_factored`. No dense ``16**k`` operator
    is ever constructed (spec §1.3).
    """
    rule_id: str
    node: int
    # leaf_index -> (16, 16) complex projector. Identity is implied on
    # unlisted leaves. Stored as a tuple of (leaf, ndarray) pairs to
    # remain hashable; reconstructed to a dict at the use site.
    projectors: tuple[tuple[int, np.ndarray], ...]
    # The substrate's canonical leaf index for the node's *type* species
    # (§1.2 bond addressing). Carried explicitly so :func:`compute_anomaly`
    # can identify the type-leaf projector by index — robust against
    # encoding-basis collisions (e.g. ``KIND_ZERO == TYPE_NAT == 8`` share
    # the same |8><8| matrix in the 16-dim local Hilbert space, so a
    # matrix-equality test would complement both projectors and produce a
    # spurious anomaly on well-typed programs).
    type_leaf: int = -1

    def as_window(self) -> dict[int, np.ndarray]:
        return {leaf: op for leaf, op in self.projectors}


# ---------------------------------------------------------------------------
# Rule -> (kind_idx, type_idx, value_set?) decomposition
# ---------------------------------------------------------------------------
#
# Each one-node typing rule projects the node's *kind* leaf onto a specific
# basis index, the *type* leaf onto a complementary projector (I - P[t]),
# and optionally the *value* leaf onto a fixed set. The triple of leaf
# projectors is the rule's symmetry generator.
#
# We restrict to the one-node rules here: the ABJ trace structure
# ``Tr( P^a { P^b, P^c } )`` on three leaves of a single AST node window
# is the cleanest operator-algebraic anomaly witness, and the multi-node
# rules (T-Var, T-Abs, T-App-Arrow, T-Obligation, ...) are picked up by
# the §12.6 Goldstone diagnostic (missing-lemma localization). The §12.1
# anomaly is about *intrinsic obstructions* — kind/type mismatches that
# cannot be repaired by adding lemmas, only by rejecting the theorem.

_ONE_NODE_RULE_SIGNATURE: dict[str, tuple[int, int, tuple[int, ...] | None]] = {
    # rule_id: (kind_basis_index, required_type, value_subset)
    # value_subset is None for rules with no value-leaf constraint.
    RULE_T_LIT_INT:   (KIND_INT,    TYPE_INT,  None),
    RULE_T_LIT_BOOL:  (KIND_BOOL,   TYPE_BOOL, None),
    RULE_T_BIN_ARITH: (KIND_BIN,    TYPE_INT,
                       (VALUE_PLUS, VALUE_MINUS, VALUE_TIMES)),
    RULE_T_BIN_CMP:   (KIND_BIN,    TYPE_BOOL,
                       (VALUE_LT, VALUE_EQ)),
    RULE_T_ZERO:      (KIND_ZERO,   TYPE_NAT,  None),
    RULE_T_NATLIT:    (KIND_NATLIT, TYPE_NAT,  None),
    RULE_T_NIL:       (KIND_NIL,    TYPE_LIST, None),
}


# ---------------------------------------------------------------------------
# Public API: extract_symmetries
# ---------------------------------------------------------------------------


def extract_symmetries(typing_H: MeraTypingHamiltonian) -> list[SymmetryGenerator]:
    """Extract candidate symmetry generators from a typing Hamiltonian.

    Each one-node typing rule at each AST node contributes one generator:
    the triple of leaf-local projectors ``(P_kind, P_type, P_value)``
    that classically commute with the rule's factored projector term on
    the well-typed manifold. The list is deterministic in
    ``typing_H.terms`` order so the anomaly polynomial is byte-stable.

    Operator-algebraic contract (spec §1.1, §12.1):
      * Generators are read off the typing Hamiltonian's leaf-projector
        structure via :data:`_ONE_NODE_RULE_SIGNATURE`. The signature
        table mirrors the rule body in
        :mod:`src.qft_pcn.logic.mera_typing_hamiltonian` exactly — no AST
        walked, no symbol parsed, no rule name interpreted beyond its
        operator pattern.
      * Leaf addressing goes through ``typing_H.meta.layout.leaf_of`` —
        the same substrate addressing the Hamiltonian itself uses
        (§1.2: bond addressing, not classical lookup).
      * Multi-node rules (T-Var, T-Abs, T-App-Arrow, T-Obligation, …) are
        skipped here; their obstructions surface via §12.6 Goldstone
        modes, not §12.1 anomalies. See module docstring.
    """
    meta = typing_H.meta
    generators: list[SymmetryGenerator] = []
    for term in typing_H.terms:
        sig = _ONE_NODE_RULE_SIGNATURE.get(term.rule_id)
        if sig is None:
            continue
        kind_idx, type_idx, value_subset = sig
        kind_leaf = meta.layout.leaf_of(term.node, "kind")
        type_leaf = meta.layout.leaf_of(term.node, "type")
        projs: list[tuple[int, np.ndarray]] = [
            (kind_leaf, leaf_proj(kind_idx)),
            (type_leaf, leaf_proj(type_idx)),
        ]
        if value_subset is not None:
            value_leaf = meta.layout.leaf_of(term.node, "value")
            projs.append((value_leaf, leaf_proj_set(list(value_subset))))
        generators.append(SymmetryGenerator(
            rule_id=term.rule_id,
            node=term.node,
            projectors=tuple(projs),
            type_leaf=type_leaf,
        ))
    return generators


# ---------------------------------------------------------------------------
# Public API: compute_anomaly
# ---------------------------------------------------------------------------


def _three_leaf_trace(state: MERA, projectors: tuple[tuple[int, np.ndarray], ...]) -> float:
    """ABJ-trace component on the product of leaf projectors.

    The generator's projectors live on distinct leaves of one node's
    window. On a product (concrete-program) MERA the leaves factorize
    (spec §1.2), so

        Tr( rho_window @ P_kind @ P_type @ P_value )
            = <P_kind> * <P_type> * <P_value>

    where each ``<P_x>`` is the single-leaf expectation read via
    :func:`mera_window_expectation_factored` (this routes through the
    causal cone for term-superposition states; for product states it
    collapses to ``state.leaf_marginal``-weighted dot products). We
    evaluate the full factored window expectation in one call — that
    primitive already handles both the product and superposition cases
    correctly (§7.4).

    The result is real-non-negative (each factor is in ``[0, 1]`` for
    diagonal projectors).
    """
    ops = {leaf: op for leaf, op in projectors}
    val = mera_window_expectation_factored(state, ops)
    return float(np.real(val))


def compute_anomaly(G: SymmetryGenerator, state: MERA) -> float:
    """ABJ trace anomaly of generator ``G`` on ``state``.

    Construction. The ABJ formula is ``A^{abc} = Tr(T^a {T^b, T^c})``.
    On the leaf-local generator ``G = (P_kind, P_type, P_value)`` the
    triple-projector trace on the node window evaluates (per
    :func:`_three_leaf_trace`) to ``<P_kind> · <P_type> · <P_value>`` —
    the classical-symmetry-aligned expectation. The **anomaly** is the
    *complementary* trace: the same generator with ``P_type`` replaced
    by ``I - P_type``,

        A(G; psi) = Tr( rho_window · P_kind · (I - P_type) · P_value )

    This is the operator-algebraic obstruction: when the rule's kind
    projector fires on a node (``<P_kind>`` ≠ 0) and the type projector
    fails to fire (``<I - P_type>`` ≠ 0), the symmetry cannot be
    preserved at any parameter setting — the ABJ trace is the
    measurement of that obstruction.

    For a well-typed program the type leaf is correctly aligned with the
    kind leaf, so ``<P_kind · (I - P_type)> = 0`` and the anomaly
    vanishes. For an ill-typed program (e.g. an ``INT`` literal whose
    type leaf carries ``BOOL``) the trace fires positive — the
    impossibility certificate.

    The ``{P_b, P_c}`` anticommutator structure is realized by
    ``P_type · P_value + P_value · P_type``; for diagonal projectors on
    disjoint leaves the two terms are equal and the factor of 2 is
    absorbed into the operator-algebraic normalization (we report the
    single-ordering trace; the anticommutator just doubles it, and the
    impossibility threshold is scaled accordingly).

    Spec §12.1 contract:
      * ``A = 0`` → no obstruction; proof search proceeds.
      * ``A ≠ 0`` → provable impossibility; the (rule_id, node) pair on
        ``G`` is the obstruction's algebraic signature.
    """
    # Build the "anomalous" projector window: same kind/value projectors,
    # but type is COMPLEMENTED. This is the operator-algebraic
    # I - P[required_type] factor in every one-node typing rule body —
    # the same complement the Hamiltonian uses to *energize* the
    # violation, here re-traced as the ABJ anomaly polynomial.
    sig = _ONE_NODE_RULE_SIGNATURE.get(G.rule_id)
    if sig is None:
        return 0.0
    _kind_idx, type_idx, _value_subset = sig
    anomalous_projs: list[tuple[int, np.ndarray]] = []
    for leaf, op in G.projectors:
        # Identify the type-leaf entry by the substrate's canonical
        # *leaf index* (§1.2 bond addressing), NOT by matrix content.
        # Matrix-equality would misfire on encoding-basis collisions —
        # e.g. ``KIND_ZERO == TYPE_NAT == 8`` produces identical |8><8|
        # projectors on the kind and type leaves of a T-Zero node, and
        # complementing both yields a spurious anomaly on a well-typed
        # program. The leaf index is unique by construction.
        if leaf == G.type_leaf:
            anomalous_projs.append((leaf, leaf_proj_one_minus(type_idx)))
        else:
            anomalous_projs.append((leaf, op))
    return _three_leaf_trace(state, tuple(anomalous_projs))


# ---------------------------------------------------------------------------
# Public API: is_anomalously_obstructed
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class AnomalyCertificate:
    """A certificate that a theorem is anomalously obstructed.

    ``generators`` lists every (rule_id, node) generator whose ABJ trace
    exceeded the floor, sorted by trace magnitude (descending) for
    deterministic surfacing. ``total_anomaly`` is the sum of those
    traces — the global obstruction mass. ``is_obstructed`` is True iff
    at least one generator fired.

    This is the §12.1 "impossibility certificate": a positive result
    (the theorem is provably unprovable from these axioms), distinct
    from a search failure.
    """
    is_obstructed: bool
    total_anomaly: float
    generators: tuple[tuple[str, int, float], ...]
    floor: float


def anomaly_polynomial(
    typing_H: MeraTypingHamiltonian,
    state: MERA,
    floor: float = DEFAULT_ANOMALY_FLOOR,
) -> AnomalyCertificate:
    """The full anomaly polynomial for ``state`` under ``typing_H``.

    Evaluates :func:`compute_anomaly` on every generator extracted from
    ``typing_H``, sums the traces above ``floor``, and returns a
    certificate. The polynomial is

        A(psi) = Σ_G  A(G; psi)

    over the candidate symmetry generators. Determinism: with a fixed
    (typing_H, state, floor) the generator list and per-generator trace
    are deterministic, and the certificate is byte-identical across runs
    (sort tie-breaks on (rule_id, node)).
    """
    generators = extract_symmetries(typing_H)
    fired: list[tuple[str, int, float]] = []
    total = 0.0
    for G in generators:
        a = compute_anomaly(G, state)
        if a > floor:
            fired.append((G.rule_id, G.node, a))
            total += a
    fired.sort(key=lambda r: (-r[2], r[0], r[1]))
    return AnomalyCertificate(
        is_obstructed=len(fired) > 0,
        total_anomaly=float(total),
        generators=tuple(fired),
        floor=floor,
    )


def is_anomalously_obstructed(
    theorem_state: MERA,
    typing_H: MeraTypingHamiltonian,
    floor: float = DEFAULT_ANOMALY_FLOOR,
) -> bool:
    """Top-level §12.1 check: is the theorem genuinely unprovable?

    Returns True iff ``anomaly_polynomial(typing_H, theorem_state)``
    has at least one generator above ``floor``. Equivalent to

        anomaly_polynomial(typing_H, state).is_obstructed

    but provided as a one-liner for the spec §12.1 acceptance test
    contract.

    A True return is a *positive* result: the theorem cannot be proved
    from these axioms (the obstruction is intrinsic to the constraint
    algebra, not a search failure). A False return does not certify
    provability — it only says §12.1 found no obstruction; proof search
    must still be attempted (or §12.6 Goldstone diagnostics consulted
    for missing-lemma candidates).
    """
    return anomaly_polynomial(typing_H, theorem_state, floor=floor).is_obstructed


__all__ = [
    "AnomalyCertificate",
    "DEFAULT_ANOMALY_FLOOR",
    "SymmetryGenerator",
    "anomaly_polynomial",
    "compute_anomaly",
    "extract_symmetries",
    "is_anomalously_obstructed",
]
