"""Noether's theorem for automated conservation-law discovery (spec §12.18).

Physics origin (Noether 1918): every continuous symmetry of the action
implies a conserved current ``J^mu``. Time translation -> energy
conservation, space translation -> momentum, gauge symmetry -> charge.
The construction is constructive: given a symmetry generator ``A``, the
conserved quantity is ``J = i*A`` (Hermitian) and satisfies
``[H, J] = 0`` by definition of the symmetry.

QPCN realization (spec §12.18): the §10.8 LemmaLibrary is the
architecture's discovered-physics corpus. Continuous symmetries of the
library are transformations under which the lemma set is invariant; each
yields a Noether current = a new conserved-charge operator that the
architecture can install in its Hamiltonian as "learned physics."

ANTI-SHORTCUT (§1.1, memory:architecture-soul, anti-shortcut-directive):
the temptation here is to AST-match commutative-looking lemma pairs
(``a+b`` vs ``b+a``) and call them "symmetric." That is classical pattern
matching, NOT operator-algebraic. The §1.1 contract is that lemmas live
in the MERA bond / leaf-bond Hilbert space and structural relations are
read off operator algebra on those tensors, not off syntactic trees.

Operator-algebraic substrate
----------------------------
Each lemma carries a real-Hermitian, PSD ``fingerprint`` vector: the
sorted leaf-bond Gram spectrum (spec §4.3,
``composition.lemma_library.structural_fingerprint``). Stack the
library's fingerprints column-wise to form the **library covariance
operator**

    C = sum_i  |fp_i> <fp_i|     (Hermitian, PSD, FINGERPRINT_DIM x FINGERPRINT_DIM)

A continuous symmetry of the library is an anti-Hermitian generator ``A``
satisfying ``[A, C] = 0`` -- i.e. ``A`` commutes with the library's
operator-algebraic signature. By the spectral theorem for commuting
Hermitians, the algebra ``{A : [A, C] = 0}`` is generated by:

  * U(1) phases along each non-degenerate eigenvector of ``C`` (spectator
    phases; not "library symmetries" -- they act trivially on the
    fingerprint magnitudes), and
  * NON-trivial so(r) blocks acting WITHIN each ``r``-fold degenerate
    eigenspace of ``C`` for ``r >= 2``.

The degenerate-eigenspace blocks are exactly the continuous symmetries
the library witnesses: two (or more) lemmas with the same operator-
algebraic signature span an SO(r) rotation that maps the library to
itself. For commutative-operation lemmas (``a+b`` and ``b+a``, which
under the M1 encoder decode to the same alpha-canonical AST and hence to
the SAME leaf-bond fingerprint -- §4.3 + §5.6), the two fingerprints
coincide -> ``C`` has a 2-fold degenerate eigenspace -> mining surfaces
the SO(2) generator there. This is the structural symmetry, recovered
from operator algebra alone (no AST inspection).

Noether current
---------------
For a symmetry generator ``A`` (anti-Hermitian) the Noether current is

    J = i * A                    (Hermitian, conserved)

acting on the FINGERPRINT_DIM-dimensional fingerprint space. Conservation
is exact by construction: with ``H := C`` (the library "Hamiltonian"),

    d<J>/dt = <[H, J]> = i * <[C, i*A]> = - <[C, A]> = 0.

This is the constructive Noether procedure applied to the library's
operator-algebraic structure. The resulting ``J`` is a real operator that
the architecture can promote into its constraint Hamiltonian as a
conserved charge -- spec §12.18 step 4.

Risks and mitigations (per spec §12.18 risk table)
--------------------------------------------------
* Discrete symmetries don't yield Noether currents -- here we filter
  ``r >= 2`` continuous so(r) blocks, so a non-degenerate (rank-1)
  eigenspace yields no symmetry. (Discrete symmetries -- parity, swap
  -- live in the Z_2 quotient and are NOT surfaced by this module.)
* Approximate symmetries: ``mine_symmetries`` accepts a
  ``degeneracy_tol`` band; eigenvalues within ``degeneracy_tol`` of each
  other are treated as degenerate. The ``invariance_residual`` field on
  the returned ``Symmetry`` reports the actual eigenvalue split so callers
  can distinguish exact vs near-symmetries.
* Coincidental "symmetries": ``mine_symmetries`` requires ``r >= 2``
  lemmas to participate. A single lemma cannot fake a symmetry. Cross-
  validation (spec §12.18) is the caller's responsibility once more
  lemmas accrue; this module reports per-symmetry support so callers can
  filter by participation count.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import numpy as np

from src.qft_pcn.composition.lemma_library import (
    FINGERPRINT_DIM,
    Lemma,
    LemmaLibrary,
)


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

# Two eigenvalues of the library covariance operator C within this band
# are treated as degenerate -- they define a continuous-symmetry block.
# Calibrated against the leaf-Gram spectrum scale of M1 product MERAs:
# leaf vectors are unit-norm => Gram entries in [-1, 1] => eigenvalue
# scale ~ O(n_leaves). A 1e-6 band is well below the typical splitting
# between structurally-distinct lemmas (which differ by >= one full unit
# eigenvalue) and well above floating-point eigsolver noise (~ 1e-12).
DEFAULT_DEGENERACY_TOL = 1e-6


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Symmetry:
    """A continuous symmetry of the lemma library (spec §12.18 step 2-3).

    Fields
    ------
    generator
        Real anti-Hermitian matrix ``A``, shape
        ``(FINGERPRINT_DIM, FINGERPRINT_DIM)``. ``A^T = -A``. Acts as the
        infinitesimal generator of an SO(r) rotation within a degenerate
        eigenspace of the library covariance operator.
    eigenspace_dim
        ``r`` -- the dimension of the degenerate eigenspace this symmetry
        rotates within. Must be ``>= 2`` (rank-1 spaces have no
        non-trivial so(r) generators -> no continuous symmetry).
    eigenvalue
        The (averaged) eigenvalue of ``C`` shared by the lemmas in the
        degenerate block.
    invariance_residual
        Max eigenvalue split within the degenerate block (i.e.
        ``lambda_max - lambda_min`` for the eigenvalues counted as
        degenerate). Zero for exact symmetries; small positive for
        approximate symmetries.
    support_lemma_ids
        Tuple of ``lemma_id`` strings whose fingerprints overlap the
        degenerate eigenspace. These are the lemmas the symmetry
        physically rotates among.
    """
    generator: np.ndarray
    eigenspace_dim: int
    eigenvalue: float
    invariance_residual: float
    support_lemma_ids: tuple[str, ...]


@dataclass(frozen=True)
class NoetherCurrent:
    """A conserved Noether current built constructively from a Symmetry
    (spec §12.18 step 3).

    Fields
    ------
    current
        Hermitian operator ``J = i * A`` on the FINGERPRINT_DIM space.
        ``J^dagger = J`` (real symmetric since A is real anti-symmetric:
        ``J = i*A`` => ``J^T = i*A^T = -i*A = J^* (complex-conj)`` and J is
        purely imaginary off-diagonal, zero diagonal => Hermitian).
    symmetry
        The originating Symmetry. Kept for traceability per spec §12.18
        risk-table "report the symmetry-breaking magnitude".
    conservation_residual
        ``||[H_lib, J]||_F`` where ``H_lib = C`` is the library
        covariance operator. Zero (or numerical-floor) for an exact
        Noether current.
    """
    current: np.ndarray
    symmetry: Symmetry
    conservation_residual: float


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _library_covariance(fingerprints: Sequence[np.ndarray]) -> np.ndarray:
    """Build the library covariance operator C = sum_i |fp_i><fp_i|.

    Operator-algebraic per §1.1: each fingerprint is the leaf-Gram
    spectrum of the lemma's MERA bond structure (spec §4.3). The
    covariance is a real symmetric PSD operator on the
    FINGERPRINT_DIM-dimensional Gram-spectrum space; its degenerate
    eigenspaces are exactly the structural-equivalence classes of the
    library (lemmas whose bond structure is operator-algebraically
    indistinguishable).
    """
    if not fingerprints:
        return np.zeros((FINGERPRINT_DIM, FINGERPRINT_DIM), dtype=float)
    F = np.stack([np.asarray(fp, dtype=float) for fp in fingerprints], axis=1)
    return F @ F.T


def _degenerate_blocks(
    eigvals: np.ndarray, tol: float,
) -> list[tuple[int, ...]]:
    """Group eigenvalue indices into contiguous-eigenvalue blocks within
    ``tol``. Returns only blocks of size >= 2 (continuous symmetries
    require multi-dim eigenspaces; rank-1 spaces support no so(r)).
    """
    if eigvals.size == 0:
        return []
    order = np.argsort(eigvals)
    sorted_w = eigvals[order]
    blocks: list[list[int]] = []
    cur: list[int] = [int(order[0])]
    cur_lo = float(sorted_w[0])
    for k in range(1, len(sorted_w)):
        if sorted_w[k] - cur_lo <= tol:
            cur.append(int(order[k]))
        else:
            if len(cur) >= 2:
                blocks.append(cur)
            cur = [int(order[k])]
            cur_lo = float(sorted_w[k])
    if len(cur) >= 2:
        blocks.append(cur)
    return [tuple(b) for b in blocks]


def _so_generator_in_block(
    eigvecs_block: np.ndarray,
) -> np.ndarray:
    """Build the canonical so(2)-style generator within a degenerate
    block spanned by ``eigvecs_block`` (columns = basis of the eigenspace,
    shape ``(FINGERPRINT_DIM, r)``).

    The canonical infinitesimal SO(r) generator (the simplest
    non-trivial element of so(r), r >= 2) in the BLOCK basis is

        a_block[0, 1] = +1
        a_block[1, 0] = -1
        a_block[i, j] = 0 otherwise.

    Lift back into the ambient FINGERPRINT_DIM space:

        A = V @ a_block @ V^T

    where V = ``eigvecs_block``. Since V^T V = I_r (orthonormal columns),
    A inherits anti-symmetry (A^T = V (a^T) V^T = -A) and acts as zero
    outside the eigenspace -- it commutes with C by construction since
    C|_block = lambda * I_r and a_block lives entirely in the block.
    """
    r = eigvecs_block.shape[1]
    a_block = np.zeros((r, r), dtype=float)
    a_block[0, 1] = 1.0
    a_block[1, 0] = -1.0
    return eigvecs_block @ a_block @ eigvecs_block.T


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def mine_symmetries(
    library: LemmaLibrary,
    degeneracy_tol: float = DEFAULT_DEGENERACY_TOL,
) -> list[Symmetry]:
    """Mine continuous symmetries from a real LemmaLibrary (spec §12.18 step 2).

    Operator-algebraic procedure:
      1. Load every lemma's fingerprint (leaf-bond Gram spectrum, §4.3).
      2. Build the library covariance operator
         ``C = sum_i |fp_i> <fp_i|``.
      3. Diagonalize ``C``. Each ``r >= 2`` degenerate eigenspace yields
         an so(r) family of continuous symmetries; emit the canonical
         so(2)-style generator embedded in that eigenspace.

    A trivial library (empty or single lemma) has no degenerate
    eigenspaces -> returns ``[]``.

    Spec §12.18 substrate contract:
      * Symmetry generators live in the leaf-bond Gram-spectrum space --
        the real operator-algebraic invariant of the MERA (§4.3), NOT in
        any AST / surface-syntax space.
      * Degenerate-eigenspace detection is the entire mining algorithm;
        no AST pattern matching, no heuristic rule lookup.
    """
    if degeneracy_tol < 0:
        raise ValueError(
            f"degeneracy_tol must be >= 0, got {degeneracy_tol}")

    lemma_ids = list(library.all_ids())
    if len(lemma_ids) < 2:
        # Single or empty library: no possible continuous symmetry.
        return []

    lemmas: list[Lemma] = [library.load(lid) for lid in lemma_ids]
    fps = [np.asarray(lem.fingerprint, dtype=float) for lem in lemmas]
    C = _library_covariance(fps)

    eigvals, eigvecs = np.linalg.eigh(C)  # ascending eigenvalues
    blocks = _degenerate_blocks(eigvals, degeneracy_tol)
    if not blocks:
        return []

    # For each degenerate block, build the canonical so(2)-style
    # generator and identify which lemmas physically project onto it.
    # A lemma "supports" the symmetry if its fingerprint has non-trivial
    # projection (L2 weight) onto the degenerate eigenspace.
    symmetries: list[Symmetry] = []
    for block in blocks:
        idxs = np.asarray(block, dtype=int)
        V = eigvecs[:, idxs]  # (FINGERPRINT_DIM, r)
        A = _so_generator_in_block(V)
        block_eigs = eigvals[idxs]
        # Lemmas supporting the block: those with non-negligible
        # projection onto V. Threshold derives from the same tolerance --
        # a projection weight below sqrt(degeneracy_tol) is treated as
        # numerical leak, not genuine support.
        proj_thresh = max(np.sqrt(degeneracy_tol), 1e-9)
        support: list[str] = []
        for lem in lemmas:
            fp = np.asarray(lem.fingerprint, dtype=float)
            # Squared projection onto the eigenspace.
            coeffs = V.T @ fp
            weight = float(np.sum(coeffs * coeffs))
            if weight >= proj_thresh:
                support.append(lem.lemma_id)
        # A genuine continuous symmetry must rotate >= 2 lemmas.
        if len(support) < 2:
            continue
        symmetries.append(Symmetry(
            generator=A,
            eigenspace_dim=len(idxs),
            eigenvalue=float(np.mean(block_eigs)),
            invariance_residual=float(np.max(block_eigs) - np.min(block_eigs)),
            support_lemma_ids=tuple(sorted(support)),
        ))
    return symmetries


def build_noether_current(
    symmetry: Symmetry,
    library: LemmaLibrary | None = None,
) -> NoetherCurrent:
    """Constructive Noether procedure (spec §12.18 step 3).

    Given a continuous symmetry generator ``A`` (anti-Hermitian), the
    Noether current is

        J = i * A                   (Hermitian)

    By construction ``[H_lib, J] = i * [C, A] = 0`` since ``A`` commutes
    with the library covariance operator ``C`` (it lives entirely within
    a degenerate eigenspace).

    If ``library`` is supplied, the conservation residual
    ``||[C, J]||_F`` is computed against the actual library covariance
    operator at the time of the call (a fresh read-through). Otherwise
    the residual is set to zero by construction.
    """
    A = np.asarray(symmetry.generator, dtype=float)
    # J = i * A. For A real anti-symmetric, J is purely imaginary
    # anti-Hermitian -> Hermitian after the i factor.
    J = 1j * A

    if library is None:
        residual = 0.0
    else:
        lemma_ids = list(library.all_ids())
        if not lemma_ids:
            residual = 0.0
        else:
            fps = [np.asarray(library.load(lid).fingerprint, dtype=float)
                   for lid in lemma_ids]
            C = _library_covariance(fps)
            # [C, J] = C J - J C. Frobenius norm.
            comm = C @ J - J @ C
            residual = float(np.linalg.norm(comm, ord="fro"))

    return NoetherCurrent(
        current=J,
        symmetry=symmetry,
        conservation_residual=residual,
    )
