"""§12.3 Binding-graph + ground-subspace proof-strategy count.

This module exposes TWO complementary estimators of the spec §12.3
"essentially-different proof strategies" count:

1. ``count_binding_graph_strategies(H, genus)`` — STRUCTURAL invariant
   of the encoded program's binding diagram (first Betti number ``b_1``
   of the use-to-binder graph, lifted to ``K = 2^{b_1}`` and ``K^g``
   via the Wen 1989 / Kitaev 2006 toric-code formula). Necessary-but-
   not-sufficient: every independent binding-loop introduces at least
   one strategy choice, but not every ground eigenvector corresponds
   to a binding-loop generator.

2. ``count_ground_subspace_strategies(H, state)`` — the GENUINE Wen /
   Kitaev ground-state degeneracy via direct spectral count on the
   §12.6 constraint matrix: ``eigvalsh`` on the Hessian ``M`` (the
   Gram matrix of ``H_t|psi>`` in the term basis), counting eigenvalues
   ``<= ground_threshold``. This is the operator-algebraic enumeration
   of independent zero modes — the dimension of the ground subspace —
   which is exactly what spec §12.3 asks for.

``count_proof_strategies(H, state, genus)`` returns BOTH estimators
as a dict so callers can compare the structural upper bound (from the
binding diagram) against the genuine ground-subspace count.

The binding-graph cycle dimension is a NECESSARY-BUT-NOT-SUFFICIENT
condition for the spec count: every independent constraint loop in the
binding diagram introduces at least one strategy choice, but not every
Hamiltonian ground-eigenvector corresponds to a binding-loop generator.

Wen 1989 (topological order), Kitaev 2006 (toric code), Nayak et al.
2008 (non-abelian anyons). A topologically ordered Hamiltonian has a
ground-state degeneracy on a genus-``g`` surface equal to ``K^g`` where
``K`` is the dimension of the Wilson-loop algebra modulo trivial loops.
For the toric code, ``K = 4`` on a torus (genus 1) — two independent
Z_2 Wilson loops, algebra dimension ``2 * 2 = 4``.

We apply the same Euler-formula machinery to the *binding diagram*
of the AST (spec §12.3):

  * vertices = AST nodes (the ``meta.children_of_node`` keys);
  * tree edges = parent-to-child links of the AST;
  * binding edges = use-to-binder links (``meta.use_to_binder``,
    converted from bid-leaf indices back to node indices via the
    ``LEAVES_PER_NODE`` / ``SPECIES_LEAF_OFFSET`` layout).

The first Betti number of this graph,

    b_1 = |E| - |V| + c                                          (1)

(where ``c`` is the number of connected components) counts independent
cycles in the binding diagram. Every binding edge that is *not* part of
the spanning tree closes a non-contractible loop — a Wilson-loop
generator. Quotienting by trivial (tree-only, contractible) loops
removes the spanning-tree subgroup; what remains is the free abelian
group generated by the ``b_1`` independent cycles.

Following the Z_2 anyonic-charge structure that gives the toric-code
``K = 2^{b_1} = 4`` on its single cycle pair, we report

    K = 2 ** b_1                                                 (2)

as the Wilson-loop algebra dimension on the binding diagram. The
genus-``g`` ground-state degeneracy of the constraint Hamiltonian is
then ``K^g`` (Wen 1989; per spec §12.3 capability statement).

This module computes ``K`` and ``K^g`` **operator-algebraically**: it
reads the Hamiltonian's ``meta`` (which encodes its symmetry structure
— the connectivity of the binding diagram) and computes the cycle-space
dimension via Euler's formula. It never enumerates AST proof variants
(spec §1.1 anti-shortcut: counting proof strategies by enumerating
proofs would be a classical-lookup shortcut that violates the
architecture soul; the binding-diagram cycle space is the entanglement-
graph invariant the spec demands).
"""
from __future__ import annotations

import warnings
from dataclasses import dataclass
from typing import Any

import numpy as np

from src.qft_pcn.logic.mera_encoding import (
    LEAVES_PER_NODE,
    SPECIES_LEAF_OFFSET,
)


@dataclass(frozen=True)
class WilsonLoopAlgebra:
    """Operator-algebraic summary of the Wilson-loop algebra on a
    constraint Hamiltonian's binding diagram (spec §12.3).

    Attributes
    ----------
    n_vertices:
        Number of nodes in the binding diagram (AST node count).
    n_edges:
        Number of undirected edges (tree edges + binding edges,
        de-duplicated; self-loops are kept as a single closed-loop
        contribution).
    n_components:
        Number of connected components of the binding diagram.
    betti_1:
        First Betti number ``b_1 = |E| - |V| + c``; the number of
        independent cycles, equivalently the number of Wilson-loop
        generators modulo trivial (contractible) loops.
    algebra_dimension:
        ``K = 2 ** b_1`` — the dimension of the Wilson-loop algebra
        modulo the trivial subgroup. Equals 1 for tree-like (acyclic)
        binding diagrams; equals ``2^b_1`` when there are ``b_1``
        independent Z_2 Wilson loops (toric-code style).
    """

    n_vertices: int
    n_edges: int
    n_components: int
    betti_1: int
    algebra_dimension: int


def _bid_leaf_to_node(bid_leaf: int) -> int:
    """Invert ``MeraLayout.leaf_of(node, 'bid')`` to recover the node.

    ``bid_leaf = LEAVES_PER_NODE * node + SPECIES_LEAF_OFFSET['bid']``
    (see ``logic/_mera_layout.py``). Pure addressing arithmetic — does
    not touch the state or AST.
    """
    return (bid_leaf - SPECIES_LEAF_OFFSET["bid"]) // LEAVES_PER_NODE


def _binding_diagram_edges(meta: Any) -> tuple[set[int], list[tuple[int, int]]]:
    """Extract the undirected binding-diagram graph (V, E) from ``meta``.

    Vertices are AST node indices ``0..meta.n_nodes-1``. Edges are:
      * tree edges from ``meta.children_of_node`` (parent--child);
      * binding edges from ``meta.use_to_binder`` (use--binder),
        with bid-leaf indices converted back to node indices.

    Each edge is stored as a sorted tuple ``(min, max)`` to canonicalize
    the undirected representation; the returned edge list contains no
    duplicates and no self-loops (a binding edge from a node to itself
    — a self-bound variable — contributes nothing to the cycle space
    of an undirected graph and is dropped).
    """
    n = int(getattr(meta, "n_nodes", 0))
    vertices: set[int] = set(range(n))

    edge_set: set[tuple[int, int]] = set()

    # Tree edges: parent -> child.
    children_of_node = getattr(meta, "children_of_node", {}) or {}
    for parent, kids in children_of_node.items():
        for child in kids:
            if parent == child:
                continue
            edge_set.add((min(parent, child), max(parent, child)))

    # Binding edges: use -> binder, recorded as (use_bid_leaf, binder_bid_leaf).
    use_to_binder = getattr(meta, "use_to_binder", {}) or {}
    for use_bid, binder_bid in use_to_binder.items():
        use_node = _bid_leaf_to_node(use_bid)
        binder_node = _bid_leaf_to_node(binder_bid)
        if use_node == binder_node:
            continue
        if use_node not in vertices or binder_node not in vertices:
            # Defensive: a stale bid-leaf reference would index outside
            # the live node range. Skip; do not invent a vertex.
            continue
        edge_set.add((min(use_node, binder_node),
                      max(use_node, binder_node)))

    return vertices, sorted(edge_set)


def _connected_components(vertices: set[int],
                          edges: list[tuple[int, int]]) -> int:
    """Count connected components via union-find on the edge list."""
    parent: dict[int, int] = {v: v for v in vertices}

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    for a, b in edges:
        union(a, b)
    roots = {find(v) for v in vertices}
    return len(roots)


def compute_wilson_loop_algebra(H: Any) -> dict:
    """Extract the Wilson-loop algebra from a constraint Hamiltonian.

    Operator-algebraic computation (spec §12.3, §1.1): reads the
    Hamiltonian's symmetry structure (its ``.meta``, the AST binding
    diagram) and computes the cycle-space dimension. Does NOT enumerate
    AST proofs, does NOT diagonalize, does NOT touch the MERA state.

    Parameters
    ----------
    H:
        A constraint Hamiltonian exposing ``.meta`` with the standard
        ``MeraEncodingMeta`` interface (``n_nodes``, ``children_of_node``,
        ``use_to_binder``). ``MeraEvalHamiltonian`` and the typing
        variant both satisfy this contract.

    Returns
    -------
    dict
        ``{"n_vertices", "n_edges", "n_components", "betti_1",
        "algebra_dimension"}`` — the algebraic data of the Wilson-loop
        algebra modulo trivial loops.

    Raises
    ------
    AttributeError
        If ``H`` has no ``.meta`` attribute providing the binding-
        diagram interface (no fallback: the spec requires extracting
        the algebra from the Hamiltonian's symmetry structure).
    """
    meta = H.meta  # AttributeError here is correct — spec §12.3 contract.

    vertices, edges = _binding_diagram_edges(meta)
    v = len(vertices)
    e = len(edges)
    c = _connected_components(vertices, edges) if v > 0 else 0

    # Euler's formula for the first Betti number of an undirected graph:
    # b_1 = |E| - |V| + |components|. Non-negative for any finite graph.
    b1 = e - v + c
    if b1 < 0:
        # Defensive: a malformed meta with parallel-edge over-counting
        # could in principle drive b_1 below zero. The cycle-space
        # dimension is by definition non-negative.
        b1 = 0

    K = 1 << b1  # 2 ** b_1; Z_2 Wilson-loop algebra dimension per generator.

    algebra = WilsonLoopAlgebra(
        n_vertices=v,
        n_edges=e,
        n_components=c,
        betti_1=b1,
        algebra_dimension=K,
    )
    return {
        "n_vertices": algebra.n_vertices,
        "n_edges": algebra.n_edges,
        "n_components": algebra.n_components,
        "betti_1": algebra.betti_1,
        "algebra_dimension": algebra.algebra_dimension,
    }


def count_binding_graph_strategies(H: Any, genus: int = 1) -> int:
    """Binding-graph cycle-space dimension ``K^genus`` for ``H`` (D12 honest scope).

    HONEST SCOPE: this counts ``K^g`` where ``K = 2^{b_1}`` is read off
    the use-to-binder binding diagram via Euler's formula. It is a
    STRUCTURAL invariant of the encoded program's binding diagram, NOT
    the spec §12.3 "essentially-different proof strategies" count
    (which requires enumerating the actual ground-subspace degeneracy
    of the constraint Hamiltonian — substrate-wide work tracked in
    EXTENSIONS).

    The binding-graph cycle dimension is a NECESSARY-BUT-NOT-SUFFICIENT
    condition for the genuine spec count: every independent constraint
    loop introduces at least one strategy choice, but not every
    Hamiltonian ground-eigenvector corresponds to a binding-loop.

    Per the topological-order analogy (Wen 1989; toric code on a torus
    has ``4 = 2^2`` ground states), the ``K^g`` formula

        N(g) = K ** g                                            (3)

    is the Wilson-loop count on a genus-``g`` surface where ``K`` is
    the algebra dimension modulo trivial loops (cf.
    ``compute_wilson_loop_algebra``).

    Parameters
    ----------
    H:
        Constraint Hamiltonian (see ``compute_wilson_loop_algebra``).
    genus:
        Topological genus parameter for the ``K^g`` scaling. ``g = 1``
        is the canonical (torus) case. ``g >= 0``; ``g = 0`` (sphere)
        gives a single representative.

    Returns
    -------
    int
        ``K ** genus`` — the binding-graph cycle-space dimension at
        the given genus.

    Raises
    ------
    ValueError
        If ``genus`` is negative (no surface of negative genus exists).
    """
    if genus < 0:
        raise ValueError(
            f"genus must be non-negative; got {genus}"
        )
    algebra = compute_wilson_loop_algebra(H)
    K = int(algebra["algebra_dimension"])
    return K ** int(genus)


def count_ground_subspace_strategies(
    H: Any,
    state: Any,
    *,
    ground_threshold: float = 1e-3,
    k: int = 10,
) -> int:
    """Genuine §12.3 ground-subspace degeneracy via §12.6 spectral count.

    Reuses the §12.6 Goldstone constraint-matrix primitive
    (``_build_constraint_matrix``): builds the symmetric PSD Hessian
    ``M`` whose entries are ``Re <psi|H_i H_j|psi>`` in the per-term
    basis. Eigenvalues of ``M`` near zero correspond to ground modes
    of the constraint Hamiltonian — independent directions along which
    the residual energy vanishes. Their multiplicity is the dimension
    of the ground subspace (Wen 1989; Kitaev 2006 toric code).

    Parameters
    ----------
    H:
        Constraint Hamiltonian exposing the ``MeraEvalHamiltonian``
        contract used by ``_build_constraint_matrix`` (term list,
        ``term_energy``).
    state:
        The MERA state to evaluate ``M`` on (the variational vacuum
        whose ground subspace we are counting).
    ground_threshold:
        Eigenvalues ``<= ground_threshold`` are counted as ground
        modes. Default ``1e-3`` matches the §12.6 near-null threshold.
    k:
        Number of smallest eigenvalues to request from the Lanczos /
        dense solver. Increase if the ground subspace is suspected to
        be larger than ``k``.

    Returns
    -------
    int
        Dimension of the ground subspace = number of eigenvalues of
        ``M`` at or below ``ground_threshold``. Always ``>= 1`` for a
        well-posed constraint Hamiltonian (the variational vacuum is
        itself a ground state, contributing one zero mode); a fully
        unconstrained Hamiltonian with empty term basis returns 1.
    """
    # Local import to avoid a module-level cycle between composition
    # primitives (goldstone.py imports broader composition surfaces).
    from src.qft_pcn.composition.goldstone import _build_constraint_matrix

    M, residuals, _terms = _build_constraint_matrix(H, state)
    n = int(M.shape[0])
    if n == 0:
        # No terms => no constraints => trivially one ground state.
        return 1

    # If EVERY residual is at or below the ground threshold, the
    # Hamiltonian is already trivially satisfied by ``state`` (no active
    # constraint). M is then the zero matrix in the term basis, whose
    # entire spectrum is zero — but this signals "no constraints", not
    # "n-fold ground degeneracy". The genuine §12.3 count of
    # essentially-distinct proofs for a tautology is 1 (reflexivity).
    res = np.asarray(residuals, dtype=float)
    if bool(np.all(res <= float(ground_threshold))):
        return 1

    # Dense path is fine for the term-basis sizes that arise here
    # (~ 8 * n_nodes); Lanczos via scipy.sparse.linalg.eigsh is used
    # only when the basis is large enough for it to pay off.
    # ``k_eff`` records the number of eigenvalues actually examined; on
    # the dense path the full spectrum is returned (k_eff = n) so the
    # saturation guard below is vacuous, exactly as it should be.
    if n <= 8 or k >= n - 1:
        eigvals = np.linalg.eigvalsh(M)
        k_eff = n
    else:
        try:
            from scipy.sparse.linalg import eigsh  # type: ignore[import-untyped]

            k_eff = min(int(k), n - 1)
            eigvals, _ = eigsh(M, k=k_eff, which="SM")
        except Exception:
            # Defensive: fall back to dense if scipy is unavailable
            # or Lanczos fails to converge (the matrix is small enough
            # for dense to be cheap anyway).
            eigvals = np.linalg.eigvalsh(M)
            k_eff = n

    # Count eigenvalues at or below the ground-mode threshold. The
    # constraint Hessian is PSD by construction (Gram of H_i|psi>),
    # so negative entries (if any) are numerical noise and still
    # qualify as ground modes.
    count = int(np.sum(np.asarray(eigvals) <= float(ground_threshold)))

    # Saturation guard: if the eigsh window was fully consumed (every
    # one of the ``k_eff`` returned eigenvalues fell below the ground
    # threshold), the true ground-subspace dimension may exceed
    # ``k_eff`` and the result is a *lower bound*, not the genuine
    # count. Warn so callers know to raise ``k``. Vacuous on the dense
    # path where ``k_eff == n`` (the full spectrum was examined).
    if count == k_eff and k_eff < n:
        warnings.warn(
            f"count_ground_subspace_strategies: ground-mode count "
            f"({count}) saturates the requested Lanczos window "
            f"k_eff={k_eff} (n={n}); the true ground-subspace "
            f"dimension may be larger. Increase ``k`` to obtain a "
            f"non-saturated estimate.",
            stacklevel=2,
        )

    # Guarantee >= 1: the variational vacuum is itself a ground state.
    return max(count, 1)


def count_proof_strategies(
    H: Any,
    state: Any,
    genus: int = 1,
    *,
    ground_threshold: float = 1e-3,
    k: int = 10,
) -> dict:
    """Genuine §12.3 proof-strategy count: both estimators side-by-side.

    Returns a dict containing both the STRUCTURAL binding-graph upper
    bound (``K^g`` from the use-to-binder Betti number) and the GENUINE
    ground-subspace degeneracy (eigvalsh near zero on the §12.6
    constraint matrix). Documenting both makes it explicit that they
    measure distinct invariants of the same constraint Hamiltonian.

    Parameters
    ----------
    H, state, genus:
        See ``count_binding_graph_strategies`` /
        ``count_ground_subspace_strategies``.
    ground_threshold, k:
        Spectral-count parameters; forwarded to
        ``count_ground_subspace_strategies``.

    Returns
    -------
    dict
        ``{"binding_graph_count": K**genus,
           "ground_subspace_count": dim(ground subspace of M),
           "genus": genus, "ground_threshold": ground_threshold}``.
    """
    binding = count_binding_graph_strategies(H, genus=genus)
    ground = count_ground_subspace_strategies(
        H, state, ground_threshold=ground_threshold, k=k,
    )
    return {
        "binding_graph_count": int(binding),
        "ground_subspace_count": int(ground),
        "genus": int(genus),
        "ground_threshold": float(ground_threshold),
    }
