"""§12.3 Topological order for a priori counting of proof strategies.

Wen 1989 (topological order), Kitaev 2006 (toric code), Nayak et al.
2008 (non-abelian anyons). A topologically ordered Hamiltonian has a
ground-state degeneracy on a genus-``g`` surface equal to ``K^g`` where
``K`` is the dimension of the Wilson-loop algebra modulo trivial loops.
For the toric code, ``K = 4`` on a torus (genus 1) — two independent
Z_2 Wilson loops, algebra dimension ``2 * 2 = 4``.

For a QPCN constraint Hamiltonian, inequivalent proof strategies are
in one-to-one correspondence with inequivalent Wilson-loop operators
on the *binding diagram* of the AST (spec §12.3):

  * vertices = AST nodes (the ``meta.children_of_node`` keys);
  * tree edges = parent-to-child links of the AST;
  * binding edges = use-to-binder links (``meta.use_to_binder``,
    converted from bid-leaf indices back to node indices via the
    ``LEAVES_PER_NODE`` / ``SPECIES_LEAF_OFFSET`` layout).

The first Betti number of this graph,

    b_1 = |E| - |V| + c                                          (1)

(where ``c`` is the number of connected components) counts independent
cycles in the binding diagram. Every binding edge that is *not* part of
the spanning tree closes a non-contractible loop — a Wilson-loop
generator. Quotienting by trivial (tree-only, contractible) loops
removes the spanning-tree subgroup; what remains is the free abelian
group generated by the ``b_1`` independent cycles.

Following the Z_2 anyonic-charge structure that gives the toric-code
``K = 2^{b_1} = 4`` on its single cycle pair, we report

    K = 2 ** b_1                                                 (2)

as the Wilson-loop algebra dimension on the binding diagram. The
genus-``g`` ground-state degeneracy of the constraint Hamiltonian is
then ``K^g`` (Wen 1989; per spec §12.3 capability statement).

This module computes ``K`` and ``K^g`` **operator-algebraically**: it
reads the Hamiltonian's ``meta`` (which encodes its symmetry structure
— the connectivity of the binding diagram) and computes the cycle-space
dimension via Euler's formula. It never enumerates AST proof variants
(spec §1.1 anti-shortcut: counting proof strategies by enumerating
proofs would be a classical-lookup shortcut that violates the
architecture soul; the binding-diagram cycle space is the entanglement-
graph invariant the spec demands).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from src.qft_pcn.logic.mera_encoding import (
    LEAVES_PER_NODE,
    SPECIES_LEAF_OFFSET,
)


@dataclass(frozen=True)
class WilsonLoopAlgebra:
    """Operator-algebraic summary of the Wilson-loop algebra on a
    constraint Hamiltonian's binding diagram (spec §12.3).

    Attributes
    ----------
    n_vertices:
        Number of nodes in the binding diagram (AST node count).
    n_edges:
        Number of undirected edges (tree edges + binding edges,
        de-duplicated; self-loops are kept as a single closed-loop
        contribution).
    n_components:
        Number of connected components of the binding diagram.
    betti_1:
        First Betti number ``b_1 = |E| - |V| + c``; the number of
        independent cycles, equivalently the number of Wilson-loop
        generators modulo trivial (contractible) loops.
    algebra_dimension:
        ``K = 2 ** b_1`` — the dimension of the Wilson-loop algebra
        modulo the trivial subgroup. Equals 1 for tree-like (acyclic)
        binding diagrams; equals ``2^b_1`` when there are ``b_1``
        independent Z_2 Wilson loops (toric-code style).
    """

    n_vertices: int
    n_edges: int
    n_components: int
    betti_1: int
    algebra_dimension: int


def _bid_leaf_to_node(bid_leaf: int) -> int:
    """Invert ``MeraLayout.leaf_of(node, 'bid')`` to recover the node.

    ``bid_leaf = LEAVES_PER_NODE * node + SPECIES_LEAF_OFFSET['bid']``
    (see ``logic/_mera_layout.py``). Pure addressing arithmetic — does
    not touch the state or AST.
    """
    return (bid_leaf - SPECIES_LEAF_OFFSET["bid"]) // LEAVES_PER_NODE


def _binding_diagram_edges(meta: Any) -> tuple[set[int], list[tuple[int, int]]]:
    """Extract the undirected binding-diagram graph (V, E) from ``meta``.

    Vertices are AST node indices ``0..meta.n_nodes-1``. Edges are:
      * tree edges from ``meta.children_of_node`` (parent--child);
      * binding edges from ``meta.use_to_binder`` (use--binder),
        with bid-leaf indices converted back to node indices.

    Each edge is stored as a sorted tuple ``(min, max)`` to canonicalize
    the undirected representation; the returned edge list contains no
    duplicates and no self-loops (a binding edge from a node to itself
    — a self-bound variable — contributes nothing to the cycle space
    of an undirected graph and is dropped).
    """
    n = int(getattr(meta, "n_nodes", 0))
    vertices: set[int] = set(range(n))

    edge_set: set[tuple[int, int]] = set()

    # Tree edges: parent -> child.
    children_of_node = getattr(meta, "children_of_node", {}) or {}
    for parent, kids in children_of_node.items():
        for child in kids:
            if parent == child:
                continue
            edge_set.add((min(parent, child), max(parent, child)))

    # Binding edges: use -> binder, recorded as (use_bid_leaf, binder_bid_leaf).
    use_to_binder = getattr(meta, "use_to_binder", {}) or {}
    for use_bid, binder_bid in use_to_binder.items():
        use_node = _bid_leaf_to_node(use_bid)
        binder_node = _bid_leaf_to_node(binder_bid)
        if use_node == binder_node:
            continue
        if use_node not in vertices or binder_node not in vertices:
            # Defensive: a stale bid-leaf reference would index outside
            # the live node range. Skip; do not invent a vertex.
            continue
        edge_set.add((min(use_node, binder_node),
                      max(use_node, binder_node)))

    return vertices, sorted(edge_set)


def _connected_components(vertices: set[int],
                          edges: list[tuple[int, int]]) -> int:
    """Count connected components via union-find on the edge list."""
    parent: dict[int, int] = {v: v for v in vertices}

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    for a, b in edges:
        union(a, b)
    roots = {find(v) for v in vertices}
    return len(roots)


def compute_wilson_loop_algebra(H: Any) -> dict:
    """Extract the Wilson-loop algebra from a constraint Hamiltonian.

    Operator-algebraic computation (spec §12.3, §1.1): reads the
    Hamiltonian's symmetry structure (its ``.meta``, the AST binding
    diagram) and computes the cycle-space dimension. Does NOT enumerate
    AST proofs, does NOT diagonalize, does NOT touch the MERA state.

    Parameters
    ----------
    H:
        A constraint Hamiltonian exposing ``.meta`` with the standard
        ``MeraEncodingMeta`` interface (``n_nodes``, ``children_of_node``,
        ``use_to_binder``). ``MeraEvalHamiltonian`` and the typing
        variant both satisfy this contract.

    Returns
    -------
    dict
        ``{"n_vertices", "n_edges", "n_components", "betti_1",
        "algebra_dimension"}`` — the algebraic data of the Wilson-loop
        algebra modulo trivial loops.

    Raises
    ------
    AttributeError
        If ``H`` has no ``.meta`` attribute providing the binding-
        diagram interface (no fallback: the spec requires extracting
        the algebra from the Hamiltonian's symmetry structure).
    """
    meta = H.meta  # AttributeError here is correct — spec §12.3 contract.

    vertices, edges = _binding_diagram_edges(meta)
    v = len(vertices)
    e = len(edges)
    c = _connected_components(vertices, edges) if v > 0 else 0

    # Euler's formula for the first Betti number of an undirected graph:
    # b_1 = |E| - |V| + |components|. Non-negative for any finite graph.
    b1 = e - v + c
    if b1 < 0:
        # Defensive: a malformed meta with parallel-edge over-counting
        # could in principle drive b_1 below zero. The cycle-space
        # dimension is by definition non-negative.
        b1 = 0

    K = 1 << b1  # 2 ** b_1; Z_2 Wilson-loop algebra dimension per generator.

    algebra = WilsonLoopAlgebra(
        n_vertices=v,
        n_edges=e,
        n_components=c,
        betti_1=b1,
        algebra_dimension=K,
    )
    return {
        "n_vertices": algebra.n_vertices,
        "n_edges": algebra.n_edges,
        "n_components": algebra.n_components,
        "betti_1": algebra.betti_1,
        "algebra_dimension": algebra.algebra_dimension,
    }


def count_proof_strategies(H: Any, genus: int = 1) -> int:
    """Number of essentially-different proof strategies for ``H`` on a
    genus-``g`` surface (spec §12.3).

    Per the topological-order analogy (Wen 1989; toric code on a torus
    has ``4 = 2^2`` ground states), the ground-state degeneracy of a
    constraint Hamiltonian on a genus-``g`` surface is

        N(g) = K ** g                                            (3)

    where ``K`` is the dimension of the Wilson-loop algebra modulo
    trivial loops (cf. ``compute_wilson_loop_algebra``). Inequivalent
    ground states are inequivalent proof homotopy classes; their count
    is the count of essentially-different proof strategies.

    Parameters
    ----------
    H:
        Constraint Hamiltonian (see ``compute_wilson_loop_algebra``).
    genus:
        Topological genus of the surface on which the degeneracy is
        computed. ``g = 1`` (the torus) is the spec's canonical case.
        ``g >= 0``; ``g = 0`` (sphere) gives a single ground state.

    Returns
    -------
    int
        ``K ** genus`` — the a-priori count of distinct proof strategies.

    Raises
    ------
    ValueError
        If ``genus`` is negative (no surface of negative genus exists).
    """
    if genus < 0:
        raise ValueError(
            f"genus must be non-negative; got {genus}"
        )
    algebra = compute_wilson_loop_algebra(H)
    K = int(algebra["algebra_dimension"])
    return K ** int(genus)
